# Window settings
[window]
opacity = 0.3
padding.x = 15
padding.y = 15

# Font settings
[font]
normal = { family = "Fira Code", style = "bold" }
size = 10

# Selection settings
[selection]
save_to_clipboard = true

[general]

# Enable live config reload
live_config_reload = true 
import = ["/home/guru/.cache/wal/colors-alacritty.toml"]
