[window]
opacity = 0.3
padding.x = 15
padding.y = 15

# Font settings
[font]
normal = { family = "Fira Code", style = "bold" }
size = 10

# Selection settings
[selection]
save_to_clipboard = true

[general]
import = ["/home/guru/.config/alacritty/catppuccin-mocha.toml"]
